format = '$time$all'

[directory]
truncate_to_repo = true

[package]
disabled = true

[hostname]
ssh_only = true

[kubernetes]
disabled = false
format = '[⎈ $context( \($namespace\))]($style) in '
style = 'blue bold'

[nodejs]
symbol = '⬢ '

[cmd_duration]
show_milliseconds = true

[time]
disabled = false
format = '[$time]($style) '
