[tools]
# from core https://mise.jdx.dev/core-tools.html
java = "temurin-21.0.6+7.0.LTS"
node = "latest"
deno = "latest"
bun = "latest"

# from registry https://mise.jdx.dev/registry.html
atuin = "latest"
biome = "latest"
codex = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
jq = "latest"
ni = "latest"
opencode = "latest"
pnpm = "latest"
ripgrep = "latest"
tbls = "latest"
yq = "latest"
zellij = "latest"

# from backends https://mise.jdx.dev/dev-tools/backends/
"github:koki-develop/gat" = "latest"
"github:stateful/runme" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
