[tools]
# from core https://mise.jdx.dev/core-tools.html
java = "temurin-21.0.6+7.0.LTS"
node = "latest"
deno = "latest"
rust = "latest"
go = "latest"

# from registry https://mise.jdx.dev/registry.html
apm = "latest"
ast-grep = "latest"
atuin = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
herdr = "latest"
hunk = "latest"
jq = "latest"
ni = "latest"
pnpm = "latest"
ripgrep = "latest"
tbls = "latest"
viteplus = "latest"
yq = "latest"

# from backends https://mise.jdx.dev/dev-tools/backends/
"github:koki-develop/gat" = "latest"
"github:stateful/runme" = "latest"

[settings]
experimental = true
