alias cd-="cd -"
alias cds="cd ~/work"
alias cds="cd ~/sandbox"
alias cat="gat"
alias ls="eza"
alias la="eza -A"
alias lt="eza --tree --level 1"
alias ll="eza -Hlo --no-user --sort=type --time-style=long-iso"
alias lla="eza -HAlo --no-user --sort=type --time-style=long-iso"

alias ng="npm ls --location=global --depth=0"
alias deps="cat package.json | jq -r '.dependencies | keys[]' | tr '\n' ' '"
alias devdeps="cat package.json | jq -r '.devDependencies | keys[]' | tr '\n' ' '"

alias gpl="git pull"
alias gps="git push"
alias gf="git fetch"
alias gs="git status --short --branch"
alias gl="git log -n 10 --date=short --pretty=format:'%C(yellow)%h %C(green)%cd %C(blue)%cn %C(reset)%s'"
alias gll="git log --date=short --pretty=format:'%C(yellow)%h %C(green)%cd %C(blue)%cn %C(reset)%s'"
alias gb="git branch"
alias gbl="git branch -a -vv"
alias ga="git add"
alias gd="git diff"
alias gdc="git diff --cached"
alias gdw="git diff --color-words"
alias gds="git diff --color-words --word-diff-regex='\\\w+|[^[:space:]]'"
alias gnew="git switch --create"
alias grs="git restore"
alias gun="git reset --staged"
alias gcm="git commit --message"
alias gini="git init && git commit --allow-empty -m 'chore: initial empty commit'"
alias gam="git commit --amend -C HEAD"
alias gcf="git commit --amend -m"
alias gg="git fetch --all --prune && git branch -vv | awk '/: gone]/{print \$1}' | xargs -r git branch -D"

alias coder="code . --reuse-window"
alias oc="opencode"
alias occ="opencode --continue"
alias pbcopy="clip.exe"
alias pbpaste="powershell.exe -command 'Get-Clipboard'"
