#!/usr/bin/env zsh

zstyle ':completion::complete:*' use-cache true
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors "${LS_COLORS}"

setopt no_beep
setopt auto_cd
setopt auto_pushd
setopt list_packed
setopt list_types
setopt pushd_ignore_dups
setopt magic_equal_subst
setopt complete_aliases
setopt extended_glob
setopt share_history
setopt extended_history
setopt inc_append_history
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_reduce_blanks

export TZ="Asia/Tokyo"
export LESS="-R"
export LANG="ja_JP.utf8"
export EDITOR="code --wait"
export FCEDIT="code --wait"

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="${HOME}/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="${HOME}/.cache"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="${HOME}/.local/share"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="${HOME}/.local/state"}

export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=100000
export SAVEHIST=100000

export DO_NOT_TRACK=1
export DISABLE_TELEMETRY=1

export ZENO_GIT_CAT="gat"
export ZENO_GIT_TREE="eza --tree"

path+=(
  "${HOME}/.cargo/bin"
  "${HOME}/.local/bin"
)

fpath+=(
  "${HOME}/.zsh/completions"
)

typeset -U path PATH

autoload -Uz colors; colors
autoload -Uz compinit; compinit
autoload -Uz promptinit; promptinit

eval "$(mise activate zsh)"
eval "$(starship init zsh)"

source "${XDG_DATA_HOME}/zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
source "${XDG_DATA_HOME}/zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
source "${XDG_DATA_HOME}/zsh/zeno/zeno.zsh"

if [[ -n $ZENO_LOADED ]]; then
  bindkey ' ' zeno-auto-snippet
  bindkey '^m' zeno-auto-snippet-and-accept-line
  bindkey '^i' zeno-completion
  bindkey '^xx' zeno-insert-snippet
  bindkey '^x '  zeno-insert-space
  bindkey '^x^m' accept-line
  bindkey '^x^z' zeno-toggle-auto-snippet
  bindkey '^xp' zeno-preprompt
  bindkey '^xs' zeno-preprompt-snippet
  bindkey '^r' zeno-smart-history-selection
  bindkey '^g' zeno-ghq-cd
fi

function zeno-git-switch() {
    BUFFER="git switch "
    CURSOR=${#BUFFER}
    zle zeno-completion
}
zle -N zeno-git-switch
bindkey '^b' zeno-git-switch

alias cdw="cd ~/work"
alias cds="cd ~/sandbox"
alias coder="code . --reuse-window"
alias ls="eza"
alias la="eza -A"
alias lt="eza --tree --level 1"
alias ll="eza -Hlo --no-user --sort=type --time-style=long-iso"
alias lla="eza -HAlo --no-user --sort=type --time-style=long-iso"
