name: ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

env:
  CI: true
  TZ: Asia/Tokyo
  DO_NOT_TRACK: 1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends --yes zsh
      - run: |
          bash -n setup.sh bin/xdg-open
          zsh -n zsh/*.zsh
      - run: shellcheck setup.sh bin/xdg-open
